flowchart TD
    classDef defaultStyle fill:#fff,stroke:#333,stroke-width:1px,color:black;
    classDef highlightStyle fill:#8df,stroke:#333,stroke-width:2px,color:black;
    RootCA["Root CA [O=Contoso, CN=Root CA]"] --> SNCCert["Encryption Cert [O=Contoso, CN=SNC]"]
    RootCA --> UsersCert["Signing Cert [O=Contoso, CN=Users]"]
    UsersCert --> U1[UserID: testuser01]
    UsersCert --> U2[UserID testuser02]
    UsersCert --> U3[UserID testuser03]
    class UsersCert,U1,U2,U3 defaultStyle;
    class RootCA,SNCCert highlightStyle;