name: Validate PowerFx references
run-name: ${{ github.actor }} validating PowerFx references
on:
  pull_request:
    branches:
      - main
    paths:
      - power-platform/power-fx/funcjson/**

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Run validation script
        id: validation_run
        run: |
          .\power-platform\power-fx\validate.ps1

  comment:  
    needs: run-powershell
    runs-on: ubuntu-latest    
    steps:
      - name: Add PR comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const errorTextOutput = `{{ steps.validation_run.outputs.reportedErrorsOutput }}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: errorTextOutput
            })
